version: 2.1

orbs:
  maven: circleci/maven@1.0.1

workflows:
  maven_test:
    jobs:
      - maven/test: # checkout, build, test, and upload test results
          context: kgrid
          settings_file: ".circleci/settings.xml"
      - deploy:
          context: kgrid

jobs:
  deploy: # mvn deploy does build, test, install, deploy (of the SNAPSHOT)

    docker:
      - image: circleci/openjdk:11.0.1-jdk

    steps:
      - checkout
      - run:
          name: Deploy
          command: mvn clean deploy -s .circleci/settings.xml